[versions]
agp = "8.7.2"
junit = "4.13.2"
appcompat = "1.7.0"
securityCrypto = "1.1.0-alpha06"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
